### ISSUE TITLE
Insecure localhost connection

### ISSUE THREAD

**Issue by ArdorDeosis** [dotnet/AspNetCore.Docs.de-de#62]
In Step 3.7 my Chrome browser at first blocked non-certified connections to localhost as insecure. A link to resources fixing this problem would be helpful.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Erste Schritte mit ASP.NET Core Blazor](https://docs.microsoft.com/de-de/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ArdorDeosis
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ArdorDeosis, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17622. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
