### ISSUE TITLE
Pages/Shared/_Layout.cshtml example does not load correctly

### ISSUE THREAD

**Issue by Pfleiderer-Adrian** [dotnet/AspNetCore.Docs.de-de#80]
Problem with AspNetCore.Docs.de-de/aspnetcore/data/ef-rp/intro.md
Pages/Shared/_Layout.cshtml exampel is not showing in the tutorial.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages mit Entity Framework Core in ASP.NET Core – Tutorial 1 bis 8](https://docs.microsoft.com/de-de/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  ?

**Comment by wadepickett** [comment]
@Rick-Anderson.  This is the /de-de/ version.  Comparing quickly to the /en-us/ it does not appear that /de-de/ updated yet and is showing some of the old original version.  Steps are not numbered, graphics are missing.

I will check in with the localization team to see what happened.

@Pfleiderer-Adrian, thanks so much for taking the time to point this issue out.  Greatly appreciated.

**Comment by wadepickett** [comment]
Example:  The /de-de/ version compared to /en-us/

/de-de/
![image](https://user-images.githubusercontent.com/10985336/99291860-4d29fc00-27f5-11eb-800d-081b3f376520.png)

/en-us/
![image](https://user-images.githubusercontent.com/10985336/99291969-75195f80-27f5-11eb-88f7-d67d6fc27f62.png)

**Comment by Rick-Anderson** [comment]
@JasonCard  this doc is not being updated.

**Comment by wadepickett** [comment]
@JasonCard, just some more info:  
The /en-us/ major update for this topic that we hope to see in the localized versions was 10 days ago.  
Here is the PR: 5.0 update - Rewrite: Razor Pages Get Started Tutorial Series by wadepickett · Pull Request #20348 · dotnet/AspNetCore.Docs (github.com)

All topics under  /aspnet/core/tutorials/razor-pages/   were updated, plus some include items at the root.

I didn't put in any sort of request to fire off a translation, so if I needed to that was my mistake.

**Comment by wadepickett** [comment]
@Rick-Anderson & @Jason Card.   I was looking at the wrong Razor Pages series /en-us/ topic for this /de-de/ version which happens to contain some of the same instruction.  So I corrected the information I provided above.  Although it is the same missing information.  Just not the right PR link.

**Comment by JasonCard** [comment]
@wadepickett @Rick-Anderson The last English update was [committed](https://github.com/dotnet/AspNetCore.Docs/commit/ec3f5a23d409d3e9724c4370a6a2ecc12737595f#diff-241984709933771b92fa4e2127ca856e1a98488614153c6c9f1673b21919a553) on Fri 11/6. For loc updates, we have a weekly cadence with handoff on Wednesdays, so last update was handed off on Wed 11/11, and ETA for loc update to be published live is Wed 11/18.

Regarding the issue where code example for *Pages/Shared/_Layout.cshtml* file is not displayed for localized topics, this is caused by source issue where MD syntax for line break is missing before the code sample, so the line break needed before the code sample is missing in loc:
[https://github.com/dotnet/AspNetCore.Docs/blob/live/aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/live/aspnetcore/data/ef-rp/intro.md)
Current (no double space or extra line for line break before the code sample):
```
Copy and paste the following code into the *Pages/Shared/_Layout.cshtml* file:
[!code-cshtml[Main](intro/samples/cu50/Pages/Shared/_Layout.cshtml?highlight=6,14,21-35,49)]
```
Should be fixed to (either double spaces or extra line to be added):
```
Copy and paste the following code into the *Pages/Shared/_Layout.cshtml* file:  

[!code-cshtml[Main](intro/samples/cu50/Pages/Shared/_Layout.cshtml?highlight=6,14,21-35,49)]
```
Once above is fixed, then the source update will be picked up on Wed 11/18 and loc pages should be fixed by Wed 11/25. If there are no other updates, then translation is not needed, so should be fixed by Thu 11/19.

**Comment by wadepickett** [comment]
@JasonCard, excellent, thanks!   I will create a tracking issue for the English version and will get that fixed on that end for this:

Copy and paste the following code into the *Pages/Shared/_Layout.cshtml* file:  

[!code-cshtml[Main](intro/samples/cu50/Pages/Shared/_Layout.cshtml?highlight=6,14,21-35,49)]

**Comment by Rick-Anderson** [comment]
> * Content: [Razor Pages mit Entity Framework Core in ASP.NET Core – Tutorial 1 bis 8](https://docs.microsoft.com/de-de/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)

How do you get the wrong page? Select the link then remove the local.

`https://docs.microsoft.com/aspnet/core/data/ef-rp/intro` redirects to your local.
`

**Comment by wadepickett** [comment]
@Rick-Anderson, I grabbed the wrong page in the draft, closed the draft and opened a proper one.  Sorry for the confusion.

**Comment by Pfleiderer-Adrian** [comment]
@wadepickett @Rick-Anderson @JasonCard Thank you all for fixing the problem so quickly! Greetings from Germany.
